spring.application.name=flight-service

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


aws.region=us-east-1
aws.dynamodb.flights-table=FlightsTable

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E2dya4jdN
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E2dya4jdN/.well-known/jwks.json


services.internal.booking-key=${BOOKING_TO_FLIGHT_INTERNAL_KEY}