spring.application.name=baggage-service
server.port=8083

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

aws.region=us-east-1
aws.dynamodb.baggage-table=BaggageTable
aws.dynamodb.baggage-booking-index=bookingId-index

services.booking.base-url=http://localhost:8081


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E2dya4jdN
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E2dya4jdN/.well-known/jwks.json



server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=never