spring.application.name=payment-service
server.port=8082

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

aws.region=us-east-1
aws.dynamodb.payments-table=PaymentsTable

services.booking.base-url=http://localhost:8081


stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.cancel-url=http://localhost:8082/payments/checkout/cancel

stripe.success-url=http://localhost:8082/payments/checkout/success?session_id={CHECKOUT_SESSION_ID}

stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:local-webhook-secret-not-set}