spring.application.name=payment-service
server.port=8082

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

aws.region=us-east-1
aws.dynamodb.payments-table=PaymentsTable

services.booking.base-url=http://localhost:8081


stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.success-url=http://localhost:5173/passenger/dashboard?payment=success
stripe.cancel-url=http://localhost:5173/passenger/dashboard?payment=cancel

stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:local-webhook-secret-not-set}


services.internal.booking-key=${PAYMENT_TO_BOOKING_INTERNAL_KEY}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E2dya4jdN
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_E2dya4jdN/.well-known/jwks.json

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=never

aws.eventbridge.bus-name=AeroLinkEventBus
aws.eventbridge.region=us-east-1